### ISSUE TITLE
Unable to open Phy due to QT error

### ISSUE THREAD

**Issue by jonahpearl** [cortex-lab/phy#1288]
Hi there -- I'm encountering an unusual QT error when trying to open phy. AFAIK, nothing changed between me having phy working and this error, but this is a shared computer so there may be deep-rooted issues in the conda install. 

The command I'm running, in the `phy2` conda environment, is:
 `phy template-gui D:\...\path\to\params.py`. 

The exact error message is:
`[16340:16344:0621/164647.773:ERROR:extension_system_qt.cpp(121)] Failed to parse extension manifest.`

I enabled QT debugging so I could get a verbose output, it doesn't seem very helpful to me (error message is on the last line, everything before seems ok): 
[phy debug qt log.txt](https://github.com/user-attachments/files/15933608/phy.debug.qt.log.txt)

I then tried the following:
-- run on a params file that worked in the past (only a few weeks ago!!) --> same error
-- uninstall the env and re-install from the command given in the README --> same error
-- uninstall the env and re-install from the yaml file --> same error.
-- `pip install PyQtWebEngine` --> same error
-- `pip uninstall pyqt5 pyqt5-tools; pip install pyqt5 pyqt5-tools pyqt5.sip` --> different error, `QWidget: Must construct a QApplication before a QWidget`. Log still doesn't seem that informative: 
[phy debug qt log after qt5sip.txt](https://github.com/user-attachments/files/15933620/phy.debug.qt.log.after.qt5sip.txt)

Again, this is on a shared Windows 10 machine, so it's entirely possible there is a weird path issue going on that I can't see. Environment info: 
[phy2_env_list.txt](https://github.com/user-attachments/files/15933642/phy2_env_list.txt)

I will probably start un-installing / re-installing anaconda next week unless someone has a good idea to debug this.

Thanks!

**Comment by zm711** [comment]
@jonahpearl,

One quick easy check would be are you sure you aren't accidentally escaping. In the log you have `\v` in your file name which could introduce a tab. I haven't seen how well Phy sanitizes Windows paths. A quick would be to cd into the folder instead.

```
cd/d D:\...\path\to\phy
phy template-gui params.py
```

Not sure which terminal you're using so I gave an example for the cmd prompt/anaconda prompt. 

I have never seen that error. Could you post the phy debug information.

so 
```
phy template-gui params.py --debug
```

**Comment by jonahpearl** [comment]
Gave it a shot -- no luck. Here is the phy debug from that try, rather than the QT logs. I'll do a re-install so I can repro the first error and see what the phy debug looks like.
[phy debug qt log after qt5sip in dir.txt](https://github.com/user-attachments/files/15933860/phy.debug.qt.log.after.qt5sip.in.dir.txt)

**Comment by zm711** [comment]
Could you just reinstall the environment from the yaml file, but limit the numpy to < 2.0. So use this as the yaml:

```yaml
name: phy2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - git
  - numpy<2.0
  - matplotlib
  - scipy
  - h5py
  - pyqt
  - pyopengl
  - pyqtwebengine
  - pytest
  - qtconsole
  - requests
  - responses
  - traitlets
  - dask
  - cython
  - pillow
  - scikit-learn
  - joblib
  - pip:
    - git+https://github.com/cortex-lab/phy.git
```

Phy is in maintenance mode rather than dev mode, so I haven't had time to try to patch things for Numpy 2.0 yet. With the QT issue I'm worried the install got nuked. So uninstall and reinstall with the above yaml info.
